name: Fetch DEX Token Details

on:
  schedule:
    - cron: '0 */2 * * *' # รันทุก 2 ชั่วโมง
  workflow_dispatch: # อนุญาตให้กดรัน Manual ได้

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: 📦 Install dependencies
        run: npm install

      - name: 🚀 Run script
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
          CMC_API_KEY: ${{ secrets.CMC_API_KEY }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: node index.js
